version: 2.1

orbs:
  python: circleci/python@1.3.0

jobs:
  noop:
    executor: python/default
    steps:
      - run:
          command: echo

workflows:
  main:
    jobs:
      - noop:
        filters:
          branches:
            ignore: gh-pages
